server:
  port: 80
  servlet:
      context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.chauncy: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug


mybatis-plus:
  type-aliases-package: com.chauncy.*.domain.po.*
  mapper-locations: classpath*:/mapper/**/*IBaseMapper.xml

#jwt:
#  header: Authorization
#  secret: mySecret
#  #token有效期一天
#  expiration: 86400
#  tokenHead: "Bearer "
